[package]
name = "aoc"
version = "0.1.0"
authors = ["Ali Roshan meidan"]
edition = "2021"
default-run = "aoc"

[lib]
proc-macro = true

[dependencies]
itertools = "0.12.0"
hashbrown = "0.14.3"

# lib proc-macro dependencies
syn = { version = "2.0.39", features = ["full"] }
quote = "1.0"
